# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ping.proto for package ''

require 'grpc'
require 'gr1d99_ke/services/ping/ping_pb'

module Gr1d99Ke
  module Services
    module Ping
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'gr1d99_ke.services.ping.Gr1d99Ke'

        rpc :Ping, PingRequest, PingReply
      end

      Stub = Service.rpc_stub_class
    end
  end
end
