# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ping.proto", :syntax => :proto3) do
    add_message "PingRequest" do
      optional :message, :string, 1
    end
    add_message "PingReply" do
      optional :message, :string, 1
    end
  end
end

PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PingRequest").msgclass
PingReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PingReply").msgclass
